// Centralizes every adjustable gameplay, rendering and scene value used by the game.
export const CONFIG = Object.freeze({
  laneOffsets: [-2.6, 0, 2.6],
  loop: {
    fixedDt: 1 / 60,
    maxFrameDelta: 0.1,
    millisecondsPerSecond: 1000,
  },
  input: {
    swipeThreshold: 30,
    tiltThreshold: 18,
    tiltRepeatDelay: 0.28,
  },
  track: {
    roadWidth: 9,
    roadThickness: 0.25,
    segmentLength: 30,
    turnArcLength: 22,
    gapLength: 4,
    keepAhead: 220,
    recycleBehind: 40,
    staticRoadLength: 180,
    laneMarkLength: 2,
    laneMarkWidth: 0.15,
    laneMarkHeight: 0.02,
    laneMarkSpacing: 4,
    laneMarkCount: 40,
    samplePoolSize: 2048,
    segmentPoolSize: 512,
    straightSampleStep: 1,
    turnSampleStep: 0.75,
    slopeAmount: 0.12,
    earlyDistanceEnd: 300,
    mediumDistanceEnd: 800,
    earlyWeights: [
      ['STRAIGHT', 0.85],
      ['SLOPE_UP', 0.08],
      ['SLOPE_DOWN', 0.07],
    ],
    mediumWeights: [
      ['STRAIGHT', 0.65],
      ['TURN_L', 0.1],
      ['TURN_R', 0.1],
      ['SLOPE_UP', 0.075],
      ['SLOPE_DOWN', 0.075],
    ],
    lateWeights: [
      ['STRAIGHT', 0.5],
      ['TURN_L', 0.15],
      ['TURN_R', 0.15],
      ['SLOPE_UP', 0.06],
      ['SLOPE_DOWN', 0.06],
      ['GAP', 0.08],
    ],
  },
  runner: {
    baseSpeed: 12.5,
    maxSpeed: 30,
    accelPerMeter: 0.0045,
    laneChangeTime: 0.14,
    jumpHeight: 2.4,
    jumpAirTime: 0.78,
    jumpRiseTime: 0.34,
    jumpFallTime: 0.44,
    slideTime: 0.72,
    inputBuffer: 0.12,
    coyoteTime: 0.1,
    hitSpeedPenalty: 0.4,
    hitRecoverTime: 1.2,
    runCollisionHeight: 1.8,
    slideCollisionHeight: 0.7,
    slideScaleY: 0.55,
    edgeBounceTime: 0.18,
    edgeBounceDistance: 0.3,
    previewSpeed: 2.4,
    previewBobHeight: 0.08,
    bodyWidth: 0.8,
    bodyHeight: 1.8,
    bodyDepth: 0.55,
    capsuleRadius: 0.32,
    capsuleLength: 0.9,
    capsuleCapSegments: 6,
    capsuleRadialSegments: 12,
    headRadius: 0.26,
    haloRadius: 0.5,
    haloSegments: 24,
    legRadius: 0.09,
    legLength: 0.7,
    legOffset: 0.17,
    legHipHeight: 0.15,
    legRunRate: 9,
    legRunAmplitude: 0.5,
    shadowRadius: 0.6,
    shadowSegments: 24,
  },
  pursuer: {
    startDistance: 18,
    maxDistance: 22,
    recoverRate: 1.6,
    hitPushBack: 4.5,
    killDistance: 0,
  },
  spawn: {
    coinGroupGapMin: 18,
    coinPerGroup: [5, 9],
    coinSpacing: 1.6,
    obstacleGapBase: 26,
    obstacleGapMin: 14,
    obstacleGapShrinkPerMeter: 0.006,
    powerUpGapMin: 120,
    powerUpGapMax: 260,
    obstacleStartDistance: 32,
    obstacleGapVariance: 8,
    obstaclePoolSize: 256,
    obstacleGroupPoolSize: 128,
    obstacleTypes: ['LOW_BARRIER', 'BEAM', 'PILLAR', 'FIRE', 'GAP'],
    coinGroupGapVariance: 14,
    coinArcProbability: 0.2,
    coinPoolSize: 512,
    powerUpPoolSize: 32,
  },
  powerUp: {
    magnetRadius: 6,
    magnetDuration: 8,
    shieldDuration: 0,
    boostDuration: 4.5,
    boostMultiplier: 1.45,
    pickupGapMin: 120,
    pickupGapMax: 260,
    pickupTypes: ['MAGNET', 'SHIELD', 'BOOST'],
  },
  collision: {
    laneHalfWidth: 1.35,
    forgivingMultiplier: 0.8,
    jumpClearance: 0.15,
    slideClearance: 0.9,
    runnerDepth: 0.55,
  },
  camera: {
    offsetBack: 7,
    offsetUp: 4.6,
    lookAhead: 12,
    lookHeight: 1.6,
    fovBase: 62,
    fovMax: 76,
    lateralFollow: 0.35,
    followRate: 8,
    near: 0.1,
    far: 500,
    shakeDuration: 0.28,
    shakeAmplitude: 0.12,
  },
  score: {
    coinValue: 10,
    distanceValue: 1,
    highScoreStorageKey: 'dunhuang-run-high-score',
  },
  scene: {
    fogNear: 60,
    fogFar: 320,
    ambientIntensity: 0.9,
    keyLightIntensity: 1.4,
    fillLightIntensity: 0.4,
    keyLightPosition: [30, 60, -20],
    fillLightPosition: [-30, 22, 40],
    roadStart: 72,
    runnerBaseHeight: 0.9,
  },
  render: {
    maxPixelRatio: 2,
    lowFpsThreshold: 45,
    lowFpsDuration: 3,
    qualityPixelRatios: [2, 1.5, 1],
  },
  art: {
    textureSize: 256,
    skyRadius: 500,
    skyWidthSegments: 32,
    skyHeightSegments: 16,
    decorationPoolSize: 64,
    decorationSpacing: 22,
    decorationSideOffset: 13,
  },
  fx: {
    particleCount: 96,
    particleLife: 0.4,
    impactDuration: 0.32,
    speedLineOpacity: 0.28,
  },
  audio: {
    coinFrequency: 880,
    coinEndFrequency: 1320,
    masterVolume: 0.08,
  },
});
