// Centralizes every adjustable gameplay, rendering and scene value used by the game.
export const CONFIG = Object.freeze({
  laneOffsets: [-2.6, 0, 2.6],
  loop: {
    fixedDt: 1 / 60,
    maxFrameDelta: 0.1,
    millisecondsPerSecond: 1000,
  },
  track: {
    roadWidth: 9,
    roadThickness: 0.25,
    segmentLength: 30,
    turnArcLength: 22,
    gapLength: 4,
    keepAhead: 220,
    recycleBehind: 40,
    staticRoadLength: 180,
    laneMarkLength: 2,
    laneMarkWidth: 0.15,
    laneMarkHeight: 0.02,
    laneMarkSpacing: 4,
    laneMarkCount: 40,
    samplePoolSize: 2048,
    segmentPoolSize: 512,
    straightSampleStep: 1,
    turnSampleStep: 0.75,
    slopeAmount: 0.12,
    earlyDistanceEnd: 300,
    mediumDistanceEnd: 800,
    earlyWeights: [
      ['STRAIGHT', 0.85],
      ['SLOPE_UP', 0.08],
      ['SLOPE_DOWN', 0.07],
    ],
    mediumWeights: [
      ['STRAIGHT', 0.65],
      ['TURN_L', 0.1],
      ['TURN_R', 0.1],
      ['SLOPE_UP', 0.075],
      ['SLOPE_DOWN', 0.075],
    ],
    lateWeights: [
      ['STRAIGHT', 0.5],
      ['TURN_L', 0.15],
      ['TURN_R', 0.15],
      ['SLOPE_UP', 0.06],
      ['SLOPE_DOWN', 0.06],
      ['GAP', 0.08],
    ],
  },
  runner: {
    baseSpeed: 12.5,
    maxSpeed: 30,
    accelPerMeter: 0.0045,
    laneChangeTime: 0.14,
    jumpHeight: 2.4,
    jumpAirTime: 0.78,
    slideTime: 0.72,
    inputBuffer: 0.12,
    coyoteTime: 0.1,
    hitSpeedPenalty: 0.4,
    hitRecoverTime: 1.2,
    previewSpeed: 2.4,
    previewBobHeight: 0.08,
    bodyWidth: 0.8,
    bodyHeight: 1.8,
    bodyDepth: 0.55,
    capsuleRadius: 0.32,
    capsuleLength: 0.9,
    capsuleCapSegments: 6,
    capsuleRadialSegments: 12,
    headRadius: 0.26,
    haloRadius: 0.5,
    haloSegments: 24,
    legRadius: 0.09,
    legLength: 0.7,
    legOffset: 0.17,
    legHipHeight: 0.15,
    legRunRate: 9,
    legRunAmplitude: 0.5,
    shadowRadius: 0.6,
    shadowSegments: 24,
  },
  pursuer: {
    startDistance: 18,
    maxDistance: 22,
    recoverRate: 1.6,
    hitPushBack: 4.5,
    killDistance: 0,
  },
  spawn: {
    coinGroupGapMin: 18,
    coinPerGroup: [5, 9],
    coinSpacing: 1.6,
    obstacleGapBase: 26,
    obstacleGapMin: 14,
    obstacleGapShrinkPerMeter: 0.006,
    powerUpGapMin: 120,
    powerUpGapMax: 260,
  },
  camera: {
    offsetBack: 7,
    offsetUp: 4.6,
    lookAhead: 12,
    lookHeight: 1.6,
    fovBase: 62,
    fovMax: 76,
    lateralFollow: 0.35,
    followRate: 8,
    near: 0.1,
    far: 500,
  },
  score: {
    coinValue: 10,
    distanceValue: 1,
  },
  scene: {
    fogNear: 60,
    fogFar: 320,
    ambientIntensity: 0.9,
    keyLightIntensity: 1.4,
    fillLightIntensity: 0.4,
    keyLightPosition: [30, 60, -20],
    fillLightPosition: [-30, 22, 40],
    roadStart: 72,
    runnerBaseHeight: 0.9,
  },
  render: {
    maxPixelRatio: 2,
  },
});
